version: '3'

services:
  front:
    build:
      context: ./hortesie_front
    volumes:
      - ./hortesie_front:/app
    environment:
      - WATCHPACK_POLLING=true
    networks:
      local-keycloak:
    env_file:
      - .env   # Limit to 512MB of memory

  platform:
    build:
      context: ./hortesie_djangoapp
    volumes:
      - ./hortesie_djangoapp:/app
    networks:
      local-keycloak:
    depends_on:
      - db
      - front
    env_file:
      - .env     # Limit to 1GB of memory

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - local-keycloak      # Limit to 1GB of memory

  nginx:
    build: ./nginx
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - "24:25"
    networks:
      local-keycloak:
    volumes:
      - ./hortesie_djangoapp/files/uploads:/hortesie_djangoapp/files/uploads
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  keycloak-postgres:
    image: postgres:latest
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    networks:
      - local-keycloak   # Limit to 1GB of memory

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    env_file:
      - .env
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      KC_HTTP_ENABLE: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USR}
      KC_DB_PASSWORD: ${POSTGRES_PW}
      KC_HOSTNAME: auth.hortesie.fr
      KC_HTTPS_CERTIFICATE_FILE: /etc/letsencrypt/live/auth.hortesie.fr/fullchain.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE:  /etc/letsencrypt/live/auth.hortesie.fr/privkey.pem
    command: 
      - start
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --verbose
    depends_on:
      - keycloak-postgres
    networks:
      local-keycloak:
        ipv4_address: 172.28.0.12
        aliases:
          - "auth.hortesie.fr"
    volumes:
      - ./keycloak/config/realm-export (5).json:/opt/keycloak/data/import/realm-config.json
      - ./keycloak/themes:/opt/keycloak/themes
      - ./certbot/conf:/etc/letsencrypt/:ro


  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      local-keycloak:
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Limit to 256MB of memory

volumes:
  postgres_data:
  keycloak_data:

networks:
  local-keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
