version: '3'

services:
  front:
    build:
      context: ./hortesie_front
    ports:
      - "3000:3000"
    volumes:
      - ./hortesie_front:/app
    environment:
      - WATCHPACK_POLLING=true
    networks:
      local-keycloak:
    env_file:
      - .env
  platform:
    build:
      context: ./hortesie_djangoapp
    volumes:
      - ./hortesie_djangoapp:/app
    ports:
      - "8000:8000"
    networks:
      local-keycloak:
    depends_on:
      - db
      - front
    env_file:
      - .env
  
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - local-keycloak

  nginx:
    build: ./nginx
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - "24:25"
    networks:
      local-keycloak:
    volumes:
      - ./hortesie_djangoapp/files/uploads:/hortesie_djangoapp/files/uploads  # Mount uploads folder
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  keycloak-postgres:
      image: postgres:latest
      volumes:
        - keycloak_data:/var/lib/postgresql/data
      env_file:
        - .env
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${POSTGRES_USR}
        POSTGRES_PASSWORD: ${POSTGRES_PW}
      networks:
        - local-keycloak
    
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    env_file:
      - .env
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: postgres
      KC_HTTP_ENABLE: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USR}
      KC_DB_PASSWORD: ${POSTGRES_PW}
      KC_HOSTNAME: auth.hortesie.fr
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command: 
      - start
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      # - --proxy-headers=forwarded
      # - --proxy=edge
    depends_on:
      - keycloak-postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      local-keycloak:
        ipv4_address: 172.28.0.12
        aliases:
          - "auth.hortesie.fr"
    volumes:
      - ./keycloak/config/realm-export (5).json:/opt/keycloak/data/import/realm-config.json
      - ./keycloak/themes:/opt/keycloak/themes
      - ./certbot/conf/live/hortesie.fr-0001/fullchain.pem:/etc/x509/https/tls.crt
      - ./certbot/conf/live/hortesie.fr-0001/privkey.pem:/etc/x509/https/tls.key
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    networks:
      local-keycloak:
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  postgres_data:
  keycloak_data:

networks:
  local-keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
