COPY package.json yarn.lock ./
COPY ./package.json /package.json 
# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application source code
COPY . .













# Expose port 3000
EXPOSE 3000

CMD ["yarn", "start"]