# Generated by Django 5.1.3 on 2024-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='motscle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ville',
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
