# Generated by Django 5.1.3 on 2024-11-09 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0003_remove_project_motscle_remove_project_ville_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTPTemplate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='hortesie_django/files/TEMPLATE_WORD_CCTP.docx')),
                ('file_versions', models.FileField(upload_to='hortesie_django/files/versions/%Y/%m/%d/TEMPLATE_WORD_CCTP.docx')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
