# Generated by Django 5.1.3 on 2024-11-09 17:44

import hortesie_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0004_cctptemplate_alter_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=hortesie_django.models.upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='vignette',
            field=models.FileField(upload_to='vignettes/projet-{id}-vignette.png'),
        ),
    ]
