# Generated by Django 5.1.3 on 2024-11-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0006_alter_project_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vignette',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
