# Generated by Django 5.1.3 on 2024-11-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0007_alter_project_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vignette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hortesie_django.photo'),
        ),
    ]
