# Generated by Django 5.1.3 on 2024-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0008_alter_project_vignette'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
