# Generated by Django 5.1.3 on 2024-11-10 13:23

import hortesie_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0011_alter_cctptemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctptemplate',
            name='file',
            field=models.FileField(upload_to=hortesie_django.models.upload_to_remove),
        ),
        migrations.AlterField(
            model_name='cctptemplate',
            name='file_versions',
            field=models.FileField(blank=True, null=True, upload_to='hortesie_django/versions/%Y/%m/%d/'),
        ),
    ]
