# Generated by Django 5.1.3 on 2024-11-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0012_alter_cctptemplate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctptemplate',
            name='file_versions',
        ),
    ]
