# Generated by Django 5.1.3 on 2024-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0013_remove_cctptemplate_file_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
