# Generated by Django 5.1.3 on 2025-08-17 22:26

import django.db.models.deletion
import hortesie_django.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortesie_django', '0014_project_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=hortesie_django.models.upload_to)),
                ('vignette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hortesie_django.photo')),
            ],
        ),
    ]
